---

- name: Update hostname
  hostname: name="{{inventory_hostname}}"

- name: Update /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
#  notify:
#    - Reboot

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}"
