---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: 'Upgrade system to the latest packages'
  apt:
    upgrade: safe

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
