raspi_config_other_options: {
  'disable_camera_led':1,
  'dtparam=act_led_trigger':'none',
  'dtparam=act_led_activelow':'off',
  'dtparam=pwr_led_trigger':'none',
  'dtparam=pwr_led_activelow':'off'
}
