- name: 'Set rc.local'
  template:
    src: rc.local.j2
    dest: /etc/rc.local

#- name: 'Set keyboard'
#  replace:
#    destfile: /etc/default/keyboard
#    regexp: '"gb"'
#    replace: '"us"'
#  ignore_errors: yes

- name: 'Set timezone to London'
  timezone:
    name: Europe/London

#- name: 'Install US locale'
#  locale_gen:
#    name: en_US.UTF-8
#    state: present

#- name: 'Set locale'
#  command: 'update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8'

- name: 'Set additional config vars'
  pi_boot_config:
  args:
    config_vals: "{{raspi_config_other_options}}"
  notify:
    - apply raspi-config
